# Define services
services:
  # Frontend service
  daisy-web:
    build:
      context: ./
      dockerfile: Dockerfile
      # args:
      #   VITE_DAISY_SERVICE_URL: http://ec2-34-227-228-41.compute-1.amazonaws.com
    image: rtunque/daisy:web-1.0.1
    # environment:
    #   DAISY_SERVICE_URL: http://127.0.0.0:8080/
    ports:
      - "80:3000"
    restart: always
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"